### ISSUE TITLE
feature request: Add CircularSliderWithChildren to documentation

### ISSUE THREAD

**Issue by kylewetton** [mnkhouri/react-circular-slider#7]
You use this class multiple times in your docs but don't make any mention of it, would probably help. Cheers!

**Comment by kylewetton** [comment]
Also, this styling makes no sense? Was that for your docs only? Would be helpful to be able to pass our own styling object to this div

`position: absolute;
    top: 25%;
    left: 50%;
    transform: translateX(-50%);
    width: 60px;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
`

**Comment by mnkhouri** [comment]
Thanks! Added this to the documentation. 

I forget why I had `width: 60px` in there. I've removed it in 75dd0bbaa940908a3353c319b26442f996fd53af.

To use your own style, it's probably easiest to just construct your own version of the CircularSliderWithChildren, since the code is so simple. The styling of that inner div is somewhat tied to the styling of the outer div, so I'm not sure how to cleanly expose it https://github.com/mnkhouri/react-circular-slider/blob/75dd0bbaa940908a3353c319b26442f996fd53af/src/index.tsx#L365-L397
